version: '3.9'

services:
  db:
    image: postgres:16
    container_name: simpler_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: simpler_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      GO_ENV: ${GO_ENV}
      DB_HOST: ${DB_HOST}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${DB_PORT}
    
    volumes:
      - ./.env:/app/.env

volumes:
  postgres_data:
